name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # каждый день в полночь UTC
  workflow_dispatch:        # ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Lu7474
          THEME: tokyonight
